// Generated by gencpp from file flexrobot_description_pkg/demo_srv.msg
// DO NOT EDIT!


#ifndef FLEXROBOT_DESCRIPTION_PKG_MESSAGE_DEMO_SRV_H
#define FLEXROBOT_DESCRIPTION_PKG_MESSAGE_DEMO_SRV_H

#include <ros/service_traits.h>


#include <flexrobot_description_pkg/demo_srvRequest.h>
#include <flexrobot_description_pkg/demo_srvResponse.h>


namespace flexrobot_description_pkg
{

struct demo_srv
{

typedef demo_srvRequest Request;
typedef demo_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct demo_srv
} // namespace flexrobot_description_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexrobot_description_pkg::demo_srv > {
  static const char* value()
  {
    return "e21fb7853ad73d6d988d6371d4fed1e2";
  }

  static const char* value(const ::flexrobot_description_pkg::demo_srv&) { return value(); }
};

template<>
struct DataType< ::flexrobot_description_pkg::demo_srv > {
  static const char* value()
  {
    return "flexrobot_description_pkg/demo_srv";
  }

  static const char* value(const ::flexrobot_description_pkg::demo_srv&) { return value(); }
};


// service_traits::MD5Sum< ::flexrobot_description_pkg::demo_srvRequest> should match 
// service_traits::MD5Sum< ::flexrobot_description_pkg::demo_srv > 
template<>
struct MD5Sum< ::flexrobot_description_pkg::demo_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexrobot_description_pkg::demo_srv >::value();
  }
  static const char* value(const ::flexrobot_description_pkg::demo_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexrobot_description_pkg::demo_srvRequest> should match 
// service_traits::DataType< ::flexrobot_description_pkg::demo_srv > 
template<>
struct DataType< ::flexrobot_description_pkg::demo_srvRequest>
{
  static const char* value()
  {
    return DataType< ::flexrobot_description_pkg::demo_srv >::value();
  }
  static const char* value(const ::flexrobot_description_pkg::demo_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexrobot_description_pkg::demo_srvResponse> should match 
// service_traits::MD5Sum< ::flexrobot_description_pkg::demo_srv > 
template<>
struct MD5Sum< ::flexrobot_description_pkg::demo_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexrobot_description_pkg::demo_srv >::value();
  }
  static const char* value(const ::flexrobot_description_pkg::demo_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexrobot_description_pkg::demo_srvResponse> should match 
// service_traits::DataType< ::flexrobot_description_pkg::demo_srv > 
template<>
struct DataType< ::flexrobot_description_pkg::demo_srvResponse>
{
  static const char* value()
  {
    return DataType< ::flexrobot_description_pkg::demo_srv >::value();
  }
  static const char* value(const ::flexrobot_description_pkg::demo_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXROBOT_DESCRIPTION_PKG_MESSAGE_DEMO_SRV_H
