// Generated by gencpp from file flexrobot_description_pkg/demo_msg.msg
// DO NOT EDIT!


#ifndef FLEXROBOT_DESCRIPTION_PKG_MESSAGE_DEMO_MSG_H
#define FLEXROBOT_DESCRIPTION_PKG_MESSAGE_DEMO_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flexrobot_description_pkg
{
template <class ContainerAllocator>
struct demo_msg_
{
  typedef demo_msg_<ContainerAllocator> Type;

  demo_msg_()
    : greeting()
    , number(0)  {
    }
  demo_msg_(const ContainerAllocator& _alloc)
    : greeting(_alloc)
    , number(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _greeting_type;
  _greeting_type greeting;

   typedef int32_t _number_type;
  _number_type number;




  typedef boost::shared_ptr< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> const> ConstPtr;

}; // struct demo_msg_

typedef ::flexrobot_description_pkg::demo_msg_<std::allocator<void> > demo_msg;

typedef boost::shared_ptr< ::flexrobot_description_pkg::demo_msg > demo_msgPtr;
typedef boost::shared_ptr< ::flexrobot_description_pkg::demo_msg const> demo_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flexrobot_description_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'flexrobot_description_pkg': ['/home/bilynbk/catkin_ws/src/flexrobot_description_pkg/msg', '/home/bilynbk/catkin_ws/devel/share/flexrobot_description_pkg/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d44a7bb82ba135859a5038705fd5c1d";
  }

  static const char* value(const ::flexrobot_description_pkg::demo_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d44a7bb82ba1358ULL;
  static const uint64_t static_value2 = 0x59a5038705fd5c1dULL;
};

template<class ContainerAllocator>
struct DataType< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexrobot_description_pkg/demo_msg";
  }

  static const char* value(const ::flexrobot_description_pkg::demo_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string greeting\n\
int32 number\n\
";
  }

  static const char* value(const ::flexrobot_description_pkg::demo_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.greeting);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct demo_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexrobot_description_pkg::demo_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexrobot_description_pkg::demo_msg_<ContainerAllocator>& v)
  {
    s << indent << "greeting: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.greeting);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXROBOT_DESCRIPTION_PKG_MESSAGE_DEMO_MSG_H
